---
- name: CRI-O | dnf repo is present
  ansible.builtin.yum_repository:
    name: CRI-O
    description: CRI-O packages
    baseurl: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/rpm/
    gpgcheck: true
    gpgkey: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_version }}/rpm/repodata/repomd.xml.key
    exclude:
      - cri-o
  become: true

- name: CRI-O | package is installed
  ansible.builtin.dnf:
    name:
      - cri-o
    disable_excludes: CRI-O
  become: true

- name: CRI-O | service is enabled
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: crio.service
    state: started
  become: true
